name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    needs: linting
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Env
        shell: bash
        run: |
          python -m pip install -e .[all]

      - name: Check and Log Environment
        shell: bash
        run: |
          python -V
          python -m pip freeze

      - name: Pylint
        shell: bash
        run: |
          python -m pip install pylint
          python -m pylint msal_requests_auth

      - name: mypy
        shell: bash
        run: |
          python -m pip install mypy types-requests
          python -m mypy msal_requests_auth

      - name: Test
        shell: bash
        run: |
          python -m pytest --cov-report term-missing --cov=msal_requests_auth --cov-report xml

      - uses: codecov/codecov-action@v3
