name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  test:
    needs: linting
    name: ${{ matrix.os }}, ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Env
        shell: bash
        run: |
          python -m pip install -e .[all]

      - name: Check and Log Environment
        shell: bash
        run: |
          python -V
          python -m pip freeze

      - name: Pylint
        shell: bash
        run: |
          python -m pip install pylint
          pylint msal_requests_auth

      - name: Test
        shell: bash
        run: |
          python -m pytest --cov-report term-missing --cov=msal_requests_auth --cov-report xml

      - uses: codecov/codecov-action@v1
